/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import arkcontrolador.ConexionMySQL;
import com.mysql.jdbc.MySQLConnection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Guille
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public String mapa = "";
    String server = "";
    String server2 = "";
    String server3 = "";
private URL url = getClass().getResource("/Imagenes/fondoBusqueda.png");
    
    String dino = "";
       String dino2 = "";
          String dino3 = "";
    String listado="";
    String sexo = "";
    Connection cn = null;
    boolean busca=true;
    ConexionMySQL mysql = new ConexionMySQL();

    private VentanaServer ven;

    public Main() throws SQLException {
        initComponents();
        panelDino.setVisible(false);
        cn = mysql.Conectar();
        txtName.setVisible(false);
        int numeroDinos = 0;
        String sqlNombreDino = "Select Nombre from nombredino";
        String numDinos = "Select count(Nombre) as Nombre from nombredino";
        PreparedStatement contarDinos = cn.prepareStatement(numDinos);
        PreparedStatement nombresDinos = cn.prepareStatement(sqlNombreDino);
        ResultSet rs = contarDinos.executeQuery();
        ResultSet rsDinos = nombresDinos.executeQuery();

        if (rs.next()) {
            numeroDinos = rs.getInt(1);
        }

        for (int i = 0; i <= numeroDinos; i++) {
            while (rsDinos.next()) {
                comboSeleccionaDino.addItem(rsDinos.getString("Nombre"));
                comboAñadeDino.addItem(rsDinos.getString("Nombre"));
                comboListadoDinos.addItem(rsDinos.getString("Nombre"));
            }
        }

        PanelBusqueda.setBackground(java.awt.Color.GREEN);
        PanelComparacion.setBackground(java.awt.Color.BLUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelBusqueda = new javax.swing.JPanel();
        comboSeleccionaServer = new javax.swing.JComboBox<>();
        comboSeleccionaDino = new javax.swing.JComboBox<>();
        comboSeleccionaSexo = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        panelDino = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        eStamina1 = new javax.swing.JLabel();
        eComida1 = new javax.swing.JLabel();
        eOxigeno1 = new javax.swing.JLabel();
        eDaño1 = new javax.swing.JLabel();
        ePeso1 = new javax.swing.JLabel();
        eVelocidad1 = new javax.swing.JLabel();
        eVida1 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        txtNombreBuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreBuscar1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PanelComparacion = new javax.swing.JPanel();
        comboServer = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnIntroducirDino = new javax.swing.JButton();
        panelDino1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtStamina = new javax.swing.JTextField();
        txtComida = new javax.swing.JTextField();
        txtOxigeno = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtDaño = new javax.swing.JTextField();
        txtVelocidad = new javax.swing.JTextField();
        txtVida = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboAñadeDino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboSeleccionaServer1 = new javax.swing.JComboBox<>();
        radioTop = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        comboListadoDinos = new javax.swing.JComboBox<>();
        comboSeleccionaServer2 = new javax.swing.JComboBox<>();
        btnBuscarListado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDinos = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboSeleccionaServer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Server", "Ragnarok", "The Island", "Volcano", "Aberration", "" }));
        comboSeleccionaServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionaServerActionPerformed(evt);
            }
        });

        comboSeleccionaDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionaDinoActionPerformed(evt);
            }
        });

        comboSeleccionaSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Sexo", "Macho", "Hembra" }));
        comboSeleccionaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionaSexoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel15.setText("Estamina");

        jLabel16.setText("Comida");

        jLabel17.setText("Oxigeno");

        jLabel18.setText("Vida");

        jLabel19.setText("Peso");

        jLabel20.setText("Daño");

        jLabel21.setText("Velocidad");

        eStamina1.setText("jLabel1");

        eComida1.setText("jLabel9");

        eOxigeno1.setText("jLabel10");

        eDaño1.setText("jLabel11");

        ePeso1.setText("jLabel12");

        eVelocidad1.setText("jLabel13");

        eVida1.setText("jLabel14");

        javax.swing.GroupLayout panelDinoLayout = new javax.swing.GroupLayout(panelDino);
        panelDino.setLayout(panelDinoLayout);
        panelDinoLayout.setHorizontalGroup(
            panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDinoLayout.createSequentialGroup()
                .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDinoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(eVelocidad1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDinoLayout.createSequentialGroup()
                        .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDinoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDinoLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eStamina1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19)
                                        .addGap(2, 2, 2))
                                    .addGroup(panelDinoLayout.createSequentialGroup()
                                        .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDinoLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eOxigeno1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDinoLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(eComida1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20))))
                            .addGroup(panelDinoLayout.createSequentialGroup()
                                .addGap(40, 89, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(24, 24, 24)
                                .addComponent(eVida1)
                                .addGap(5, 5, 5)))
                        .addGap(28, 28, 28)
                        .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eDaño1)
                            .addComponent(ePeso1))))
                .addGap(17, 17, 17))
        );
        panelDinoLayout.setVerticalGroup(
            panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(eStamina1)
                    .addComponent(jLabel19)
                    .addComponent(ePeso1))
                .addGap(16, 16, 16)
                .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(eComida1)
                    .addComponent(jLabel20)
                    .addComponent(eDaño1))
                .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDinoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(eOxigeno1)
                            .addComponent(jLabel21)
                            .addComponent(eVelocidad1)))
                    .addGroup(panelDinoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(panelDinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eVida1)
                            .addComponent(jLabel18))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        txtName.setText("jLabel1");

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        txtNombreBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscar1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jButton2.setText("Buscar Solo por Nombre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSeleccionaServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSeleccionaDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSeleccionaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(408, Short.MAX_VALUE))
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 337, Short.MAX_VALUE))))
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(btnBorrar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(125, 125, 125)
                        .addComponent(panelDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(txtName)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(panelDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNombreBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addContainerGap())
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(comboSeleccionaServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSeleccionaDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSeleccionaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Buscar Dino Top", PanelBusqueda);

        comboServer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Server", "Ragnarok", "The Island", "Volcano", "Aberration", "" }));
        comboServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboServerActionPerformed(evt);
            }
        });

        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelComparacionLayout = new javax.swing.GroupLayout(PanelComparacion);
        PanelComparacion.setLayout(PanelComparacionLayout);
        PanelComparacionLayout.setHorizontalGroup(
            PanelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComparacionLayout.createSequentialGroup()
                .addGroup(PanelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelComparacionLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelComparacionLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(comboServer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        PanelComparacionLayout.setVerticalGroup(
            PanelComparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelComparacionLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(comboServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mostrar dos Dinos Top", PanelComparacion);

        btnIntroducirDino.setText("Añadir Dino");
        btnIntroducirDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirDinoActionPerformed(evt);
            }
        });

        jLabel22.setText("Estamina");

        jLabel23.setText("Comida");

        jLabel24.setText("Oxigeno");

        jLabel25.setText("Vida");

        jLabel26.setText("Peso");

        jLabel27.setText("Daño");

        jLabel28.setText("Velocidad");

        javax.swing.GroupLayout panelDino1Layout = new javax.swing.GroupLayout(panelDino1);
        panelDino1.setLayout(panelDino1Layout);
        panelDino1Layout.setHorizontalGroup(
            panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDino1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(panelDino1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDino1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOxigeno))
                    .addGroup(panelDino1Layout.createSequentialGroup()
                        .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDino1Layout.createSequentialGroup()
                                .addComponent(txtStamina, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(txtComida, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDino1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDino1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        panelDino1Layout.setVerticalGroup(
            panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDino1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(txtStamina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(txtComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel28)
                    .addComponent(txtOxigeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre");

        comboAñadeDino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAñadeDinoActionPerformed(evt);
            }
        });

        jLabel2.setText("Dino");

        jLabel3.setText("Servidor");

        comboSeleccionaServer1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Server", "Ragnarok", "The Island", "Volcano", "Aberration", "" }));
        comboSeleccionaServer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionaServer1ActionPerformed(evt);
            }
        });

        radioTop.setText("Top");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(comboSeleccionaServer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombre))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioTop)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(comboAñadeDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIntroducirDino)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelDino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboSeleccionaServer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAñadeDino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(radioTop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntroducirDino)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Introducir Dino", jPanel1);

        comboListadoDinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListadoDinosActionPerformed(evt);
            }
        });

        comboSeleccionaServer2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Server", "Ragnarok", "The Island", "Volcano", "Aberration", "" }));
        comboSeleccionaServer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionaServer2ActionPerformed(evt);
            }
        });

        btnBuscarListado.setText("Buscar");
        btnBuscarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListadoActionPerformed(evt);
            }
        });

        txaDinos.setEditable(false);
        txaDinos.setColumns(20);
        txaDinos.setRows(5);
        jScrollPane1.setViewportView(txaDinos);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSeleccionaServer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboListadoDinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarListado)
                    .addComponent(jButton1))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboSeleccionaServer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboListadoDinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnBuscarListado)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listado De dinos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboServerActionPerformed

        int numCombo = comboServer.getSelectedIndex();

        if (numCombo == 0) {
            mapa = "";
        } else {
            mapa = String.valueOf(comboServer.getSelectedItem());
        }


    }//GEN-LAST:event_comboServerActionPerformed


    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed

        if (mapa.equals("")) {
            showMessageDialog(null, "¡¡Selecciona un Servidor!!");
        } else {
            try {
                ven = new VentanaServer(mapa);
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            ven.setVisible(true);
        }

    }//GEN-LAST:event_btnGoActionPerformed

    private void comboSeleccionaDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionaDinoActionPerformed

        dino = String.valueOf(comboSeleccionaDino.getSelectedItem());

    }//GEN-LAST:event_comboSeleccionaDinoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
//Preparamos la consulta sql, primero tenemos que validar todos los campos
        if (busca) {
       
        PreparedStatement dinoTop;
        //Validacion Final....Lo que hace el boton vaya...
        if (server.equals("")) {
            showMessageDialog(null, "¡¡El servidor no esta seleccionado!!");
        } else if (dino.equals("")) {
            showMessageDialog(null, "¡¡El Dino no esta seleccionado!!");
        } else if (sexo.equals("")) {
            showMessageDialog(null, "¡¡El Sexo no esta seleccionado!!");
        } else {
            try {
                String sqlNombreDino = "Select Stamina,Comida,Oxigeno,Peso,Daño,Velocidad,Vida,Mote FROM dinos Where Sexo='" + sexo + "' AND Nombre ='" + dino + "' AND Server = '" + server + "' AND Mote LIKE '%"+txtNombreBuscar.getText()+"%';";
                dinoTop = cn.prepareStatement(sqlNombreDino);
                ResultSet rsDinos = dinoTop.executeQuery();
                if (rsDinos.next()) {
                   txtName.setVisible(true);
                    int Stamina = rsDinos.getInt("Stamina");
                    int comida = rsDinos.getInt("Comida");
                    int Oxigeno = rsDinos.getInt("Oxigeno");
                    int Peso = rsDinos.getInt("Peso");
                    int Daño = rsDinos.getInt("Daño");
                    int Velocidad = rsDinos.getInt("Velocidad");
                    int Vida = rsDinos.getInt("Vida");
                    String Mote = rsDinos.getString("Mote");
                     txtNombreBuscar.setText(Mote);
                    panelDino.setVisible(true);
                    eStamina1.setText(String.valueOf(Stamina));
                    eComida1.setText(String.valueOf(comida));
                    eOxigeno1.setText(String.valueOf(Oxigeno));
                    ePeso1.setText(String.valueOf(Peso));
                    eDaño1.setText(String.valueOf(Daño));
                    eVelocidad1.setText(String.valueOf(Velocidad));
                    eVida1.setText(String.valueOf(Vida));
                    txtName.setText(Mote);
                }else{
                       showMessageDialog(null, "No se ha encontrado Dino");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void comboSeleccionaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionaSexoActionPerformed
        int numComboSexo = comboSeleccionaSexo.getSelectedIndex();

        if (numComboSexo == 0) {
            sexo = "";
        } else {
            sexo = String.valueOf(comboSeleccionaSexo.getSelectedItem());

        }
    }//GEN-LAST:event_comboSeleccionaSexoActionPerformed

    private void comboSeleccionaServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionaServerActionPerformed
        int numComboServer = comboSeleccionaServer.getSelectedIndex();
        if (numComboServer == 0) {
            server = "";
        } else {
            server = String.valueOf(comboSeleccionaServer.getSelectedItem());
        }
    }//GEN-LAST:event_comboSeleccionaServerActionPerformed

    private void comboAñadeDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAñadeDinoActionPerformed

        dino2 = String.valueOf(comboAñadeDino.getSelectedItem());
    }//GEN-LAST:event_comboAñadeDinoActionPerformed

    private void comboSeleccionaServer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionaServer1ActionPerformed
        int numComboServer = comboSeleccionaServer1.getSelectedIndex();
        if (numComboServer == 0) {
            server2 = "";
        } else {
            server2 = String.valueOf(comboSeleccionaServer1.getSelectedItem());
        }
    }//GEN-LAST:event_comboSeleccionaServer1ActionPerformed

    private void comboSeleccionaServer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionaServer2ActionPerformed
        int numComboServer = comboSeleccionaServer2.getSelectedIndex();
        if (numComboServer == 0) {
            server3 = "";
        } else {
            server3 = String.valueOf(comboSeleccionaServer2.getSelectedItem());
        }
    }//GEN-LAST:event_comboSeleccionaServer2ActionPerformed

    private void btnIntroducirDinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirDinoActionPerformed
        String top = "";
        if (radioTop.isSelected()) {
            top = "1";
        } else {
            top = "0";
        };

        try {
            String sqlIntroducirDino = "Insert into dinos (Nombre,Stamina,Comida,Oxigeno,Peso,Daño,Velocidad,Vida,Mote,Top,server) Values('" + dino2 + "' ," + txtStamina.getText() + "," + txtComida.getText() + "," + txtOxigeno.getText() + "," + txtPeso.getText() + "," + txtDaño.getText() + "," + txtVelocidad.getText() + "," + txtVida.getText() + ",'" + txtNombre.getText() + "'," + top + " ,'" + server2+ "')";
            PreparedStatement nuevoDino = cn.prepareStatement(sqlIntroducirDino);
            nuevoDino.executeUpdate();
            txtNombre.setText("");
            txtStamina.setText("");
            txtComida.setText("");
            txtOxigeno.setText("");
            txtPeso.setText("");
            txtDaño.setText("");
            txtVida.setText("");
            txtVelocidad.setText("");
            comboSeleccionaServer1.setSelectedIndex(0);
            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        showMessageDialog(null, dino2+" introducido en " + server2);


    }//GEN-LAST:event_btnIntroducirDinoActionPerformed

    private void btnBuscarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListadoActionPerformed
        listado = "";

        try {

            /*
            Boton para mostrar en lista los dinos
             */
            String sqlDino = "Select Stamina,Comida,Oxigeno,Peso,Daño,Velocidad,Vida,Mote FROM dinos Where Server = '" + server3 + "' And Nombre = '" + dino3 + "'";
            PreparedStatement listaDinos = cn.prepareStatement(sqlDino);
            ResultSet rsDinos = listaDinos.executeQuery();
  
            rsDinos.first();
            do {
                
                int Stamina = rsDinos.getInt("Stamina");
                int Comida = rsDinos.getInt("Comida");
                int Oxigeno = rsDinos.getInt("Oxigeno");
                int Peso = rsDinos.getInt("Peso");
                int Daño = rsDinos.getInt("Daño");
                int Velocidad = rsDinos.getInt("Velocidad");
                int Vida = rsDinos.getInt("Vida");
                String Mote = rsDinos.getString("Mote");

                listado += "-----------------------------------------\n";
                listado += dino3 + "------- Nombre=" + Mote + "\n";
                listado += "Estamina =" + Stamina + "      Peso =" + Peso + "\n";
                listado += "Comida =" + Comida + "      Daño =" + Daño + "\n";
                listado += "Oxigeno =" + Oxigeno + "      Velocidad =" + Velocidad + "\n";
                listado += "               Vida =" + Vida + "\n";
                listado += "-----------------------------------------\n";
                
            } while ((rsDinos.next()));
    
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            showMessageDialog(null, "No hay ningun Dinosaurio de tipo "+dino3+" en "+server3);
            txaDinos.setText("");
        }
        txaDinos.setText(listado);


    }//GEN-LAST:event_btnBuscarListadoActionPerformed

    private void comboListadoDinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListadoDinosActionPerformed
        dino3 = String.valueOf(comboListadoDinos.getSelectedItem());
    }//GEN-LAST:event_comboListadoDinosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 txaDinos.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        try {                                          
            String sqlBorrarDino = "DELETE FROM dinos Where Server = '"+server+" 'AND Sexo='"+sexo+"' AND Nombre ='"+dino+"' AND Mote ='"+txtNombreBuscar.getText()+"';";
            PreparedStatement nuevoDino = cn.prepareStatement(sqlBorrarDino);
                nuevoDino.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
       
                    
                    panelDino.setVisible(false);
                    eStamina1.setText("");
                    eComida1.setText("");
                    eOxigeno1.setText("");
                    ePeso1.setText("");
                    eDaño1.setText("");
                    eVelocidad1.setText("");
                    eVida1.setText("");
                    txtName.setText("");
                    txtName.setVisible(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed

    private void txtNombreBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String sqlNombreDino = "Select Stamina,Comida,Oxigeno,Peso,Daño,Velocidad,Vida,Mote,Server,Nombre,Sexo FROM dinos Where Mote LIKE '%"+txtNombreBuscar1.getText()+"%';";
            PreparedStatement dinoTop2 = cn.prepareStatement(sqlNombreDino);
            ResultSet rsDinos = dinoTop2.executeQuery();
            if (rsDinos.next()) {
                txtName.setVisible(true);
                int Stamina = rsDinos.getInt("Stamina");
                int comida = rsDinos.getInt("Comida");
                int Oxigeno = rsDinos.getInt("Oxigeno");
                int Peso = rsDinos.getInt("Peso");
                int Daño = rsDinos.getInt("Daño");
                int Velocidad = rsDinos.getInt("Velocidad");
                int Vida = rsDinos.getInt("Vida");
                String Nombre =rsDinos.getString("Nombre");
                String Server =rsDinos.getString("Server");
                String Sexo=rsDinos.getString("Sexo");
                String Mote = rsDinos.getString("Mote");
                
                txtNombreBuscar1.setText(Mote);
                txtNombreBuscar.setText(Mote);
                panelDino.setVisible(true);
                eStamina1.setText(String.valueOf(Stamina));
                eComida1.setText(String.valueOf(comida));
                eOxigeno1.setText(String.valueOf(Oxigeno));
                ePeso1.setText(String.valueOf(Peso));
                eDaño1.setText(String.valueOf(Daño));
                eVelocidad1.setText(String.valueOf(Velocidad));
                eVida1.setText(String.valueOf(Vida));
                txtName.setText(Mote);
               for (int i = 0; i < comboSeleccionaServer.getModel().getSize(); i++) {
	 String obj = comboSeleccionaServer.getModel().getElementAt(i);
	if(obj.equals(Server)){
		comboSeleccionaServer.setSelectedIndex(i);
	}
}
                     for (int i = 0; i < comboSeleccionaDino.getModel().getSize(); i++) {
	 String obj = comboSeleccionaDino.getModel().getElementAt(i);
	if(obj.equals(Nombre)){
		comboSeleccionaDino.setSelectedIndex(i);
	}
}
                           for (int i = 0; i < comboSeleccionaSexo.getModel().getSize(); i++) {
	 String obj = comboSeleccionaSexo.getModel().getElementAt(i);
	if(obj.equals(Sexo)){
		comboSeleccionaSexo.setSelectedIndex(i);
	}
}
            }
            }catch(SQLException e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JPanel PanelComparacion;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarListado;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnIntroducirDino;
    private javax.swing.JComboBox<String> comboAñadeDino;
    private javax.swing.JComboBox<String> comboListadoDinos;
    private javax.swing.JComboBox<String> comboSeleccionaDino;
    private javax.swing.JComboBox<String> comboSeleccionaServer;
    private javax.swing.JComboBox<String> comboSeleccionaServer1;
    private javax.swing.JComboBox<String> comboSeleccionaServer2;
    private javax.swing.JComboBox<String> comboSeleccionaSexo;
    private javax.swing.JComboBox<String> comboServer;
    private javax.swing.JLabel eComida1;
    private javax.swing.JLabel eDaño1;
    private javax.swing.JLabel eOxigeno1;
    private javax.swing.JLabel ePeso1;
    private javax.swing.JLabel eStamina1;
    private javax.swing.JLabel eVelocidad1;
    private javax.swing.JLabel eVida1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelDino;
    private javax.swing.JPanel panelDino1;
    private javax.swing.JRadioButton radioTop;
    private javax.swing.JTextArea txaDinos;
    private javax.swing.JTextField txtComida;
    private javax.swing.JTextField txtDaño;
    private javax.swing.JLabel txtName;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtNombreBuscar1;
    private javax.swing.JTextField txtOxigeno;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtStamina;
    private javax.swing.JTextField txtVelocidad;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables

}
